baseURL: "https://unwiredcouch.com"
languageCode: "en"
DefaultContentLanguage: "en"
title: "unwiredcouch.com"
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
Author:
  Name: Daniel Schauenberg
  Email: d@unwiredcouch.com
markup:
  goldmark:
    renderer:
      unsafe: true
relativeURLs: true
mediaTypes:
  "application/atom":
    suffixes:
      - "xml"
outputFormats:
  Atom:
    mediaType: "application/atom"
    baseName: "atom"
    isPlainText: false

outputs:
  home:
    - "HTML"
    - "RSS"
    - "Atom"
