baseURL: "https://unwiredcouch.com"
languageCode: "en"
DefaultContentLanguage: "en"
title: "unwiredcouch.com"
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
permalinks:
  /: /:year/:month/:day/:filename
uglyurls: true
markup:
  goldmark:
    renderer:
      unsafe: true
