baseURL: "https://unwiredcouch.com"
languageCode: "en"
DefaultContentLanguage: "en"
title: "unwiredcouch.com"
summarylength: 10
enableEmoji: false
enableRobotsTXT: false
Author:
  Name: Daniel Schauenberg
  Email: d@unwiredcouch.com
markup:
  goldmark:
    renderer:
      unsafe: true
relativeURLs: true
mediaTypes:
  "application/atom":
    suffixes:
      - "xml"
outputFormats:
  Atom:
    mediaType: "application/atom"
    baseName: "atom"
    isPlainText: false

outputs:
  home:
    - "HTML"
    - "RSS"
    - "Atom"

params:
  homepageSections:
    - title: Writing
      section: posts
    - title: Art
      section: art
    - title: Reading
      section: reading
    - title: Talks
      section: talks
