baseURL: "https://unwiredcouch.com"
languageCode: "en"
DefaultContentLanguage: "en"
title: "unwiredcouch.com"
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
relativeURLs: true
