name: CI

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    name: site build
    env:
      HUGO_VERSION: 0.88.1

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo apt-get update && sudo apt-get install -y imagemagick
        
    - name: software versions
      run: |
        hugo version
    - uses: actions/checkout@v1

    - name: resize images
      run: |
        make images
        
    - name: Build site into the docs/ folder
      run: |
        hugo --destination docs
        
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ assets/ 
        git commit -m "[skip ci] update site build" --allow-empty
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.event.pull_request.head.ref }}
