name: CI
on: [push]

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb
    - name: software versions
      run: |
        pandoc --version
    - uses: actions/checkout@v1
    - name: Build the site into the docs/ folder
      run: |
        SITEDIR=docs make
