name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    types: [opened, synchronize, labeled]

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: set variables
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: vars
    - name: install dependencies
      run: |
        sudo wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
      sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
    - name: software versions
      run: |
        hugo version
    - uses: actions/checkout@v1
    - name: Build site into the docs/ folder
      run: |
        hugo --destination docs
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "update site build"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.vars.outputs.branch }}
