name: CI
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: set variables
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: vars
    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb
    - name: software versions
      run: |
        pandoc --version
    - uses: actions/checkout@v1
    - name: Build the site into the docs/ folder
      run: |
        SITEDIR=docs make
    - name: check post list
      run: |
        cat .allposts.yml
        cat .allposts.psv
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "update site build"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.vars.outputs.branch }}
