name: CI
on: [push]

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: find software
      run: |
        find /opt -name "*cabal*"
        find /opt -name "*ghc*"
    - name: set up haskell path
      run: |
        echo "::add-path::/opt/ghc/8.0.2/bin"
        echo "::add-path::/opt/ghc/bin"
    - name: env debugging
      run: |
        echo $PATH
        printenv
        ghc --version
        cabal --version
    - name: install dependencies
      run: |
        cabal update
        cabal install pandoc
    - name: software versions
      run: |
        pandoc --version
    - uses: actions/checkout@v1
    - name: Build the site into the docs/ folder
      run: |
        SITEDIR=docs make
