name: CI
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: set variables
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: vars
      
    - name: set URL prefix variable
      shell: bash
      run: echo "##[::set-env name=URL_PREFIX::/unwiredcouch.com]"
      id: envvars
      if: github.ref != 'refs/heads/master'
      
    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb
    - name: software versions
      run: |
        pandoc --version
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
        id: go
    - uses: actions/checkout@v1
    - name: Build site into the docs/ folder
      run: |
        SITEDIR=docs make all
    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "update site build"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.vars.outputs.branch }}
