name: CI
on: [push]

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: find cabal
      run: find /opt -name "*cabal*"
    - name: install dependencies
      run: /opt/cabal/bin/cabal install pandoc
    - name: software versions
      run: |
        pandoc --version
    - uses: actions/checkout@v1
    - name: Build the site into the docs/ folder
      run: |
        SITEDIR=docs make
